######################################################################
# Automatically generated by qmake (2.01a) Fr 21. Nov 13:39:42 2008
######################################################################

QT += testlib xml
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../PJobFile
INCLUDEPATH += . ../PJobFile
LIBS += -L../PJobFile -lPJobFile

win32{
	build_pass:CONFIG(debug, debug|release) {
		LIBS += -L../PJobFile/debug
	} else {
		LIBS += -L../PJobFile/release
	}
}
# Input
HEADERS += TestPJobFile.h
SOURCES += main.cpp TestPJobFile.cpp
