######################################################################
# Automatically generated by qmake (2.01a) Fr 12. Sep 11:39:51 2008
######################################################################

PHOTOSS_ROOT = ..\..
include(../PQueue.pri)

QT += testlib script xml
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../PQueueModel ../CondorC++Adapter ../../PJobFile/PJobFile
INCLUDEPATH += . ../PQueueModel ../CondorC++Adapter ../../PJobFile/PJobFile
LIBS += -L.. -L../Gui -L../PQueueModel -lPQueueModel -L../../PJobFile/PJobFile -lPJobFile -L../CondorC++Adapter -lCondorC++Adapter

win32-msvc2005{
    LIBS += -lclapack
}else{
    LIBS +=  -llapack -lblas -lf2c
}
macx:LIBS += -framework Glut -framework veclib

#win32{
       build_pass:CONFIG(debug, debug|release) {
               LIBS += -L../../PJobFile/PJobFile/debug -L../CondorC++Adapter/debug -L../PQueueModel/debug
       } else {
               LIBS += -L../../PJobFile/PJobFile/release -L../CondorC++Adapter/release -L../PQueueModel/release
       }
#}

# Input
HEADERS += TestPhotossJob.h
SOURCES += main.cpp TestPhotossJob.cpp

#PRE_TARGETDEPS += ../PJobFile/libPJobFile.a ../PQueueModel/libPQueueModel.a ../CondorC++Adapter/libCondorC++Adapter.a
